name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kremi151/android-ndk:android-31-jdk11
    steps:
      - name: Pre-checkout
        run: apk add git
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./gradlew :lib:assembleRelease -x test
      - name: Validate
        run: ./gradlew detekt :lib:testReleaseUnitTest
      - name: Report detekt findings
        uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        with:
          path: '${{ github.workspace }}/lib/build/reports/detekt/detekt.xml'
        if: always()
      - name: Report test results
        uses: ashley-taylor/junit-report-annotations-action@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "${{ github.workspace }}/lib/build/test-results/**/*.xml"
        if: always()
      - name: Publish Maven artifact
        run: ./gradlew :lib:publish
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: kremi151
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'pull_request' }}
      - name: Cleanup old snapshot versions
        uses: actions/delete-package-versions@v3
        with:
          min-versions-to-keep: 10
          delete-only-pre-release-versions: "true"
        continue-on-error: true
        if: ${{ github.event_name != 'pull_request' }}
